### ISSUE TITLE
gradlew samples not working on xubuntu 16 system

### ISSUE THREAD

**Issue by Gerardwx** [FXyz/FXyz#32]
```
gweatherby@boxcode:/hard/FXyz/Fxyz-Samples$ ./gradlew run

FAILURE: Build failed with an exception.

* Where:
Build file '/hard/FXyz/Fxyz-Samples/build.gradle' line: 35

* What went wrong:
A problem occurred evaluating root project 'Fxyz-Samples'.
> Could not get unknown property 'fxyz_sampler_mainClass' for root project 'Fxyz-Samples' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

[info.txt](https://github.com/FXyz/FXyz/files/1938389/info.txt)

```

**Comment by jperedadnr** [comment]
I've just downloaded the project from the repository, and running from the samples root folder`./gradlew run` works fine for me on Mac and Windows.

Can you clean  (remove .gradle and build folders) the project and try again?

**Comment by jperedadnr** [comment]
I've just done a PR to move the gradle wrapper to the root, so you could run directly from FXyz root `./gradlew run`.

**Comment by davidcorcoran** [comment]
@jperedadnr It's not working in Linux because you have the directory "Fxyz-Samples" checked in but when you run `./gradlew assemble` it creates a directory "FXyz-Samples". So you end up with both directories in Linux. Obviously Mac and Windows have case-insensitive file systems so that's why it was working for you.

To get `./gradlew run` to work for me I did this:
```
git clone git@github.com:FXyz/FXyz.git
cd FXyz/
mv Fxyz-Samples/ FXyz-Samples
./gradlew assemble
./gradlew run
```
Which seems to confirm the problem. I'd suggest changing the checked in directory to "FXyz-Samples" to fix. This might help: https://stackoverflow.com/a/3011723/190452

**Comment by jperedadnr** [comment]
@davidcorcoran Thanks David for the link. 

I've just raised https://github.com/FXyz/FXyz/pull/37 that fixes the "Fxyz-Samples" name. Feel free to review.

**Comment by Birdasaur** [comment]
This is fine. I like it better with capital letters for FX anyways.
