### ISSUE TITLE
New Artifact: FXyz-Importers

### ISSUE THREAD

**Issue by jperedadnr** [FXyz/FXyz#38]
Create new artifact that will provide loaders/importers of complex 3D models with different formats

See https://github.com/javafxports/openjdk-jfx/issues/203

As a first step, the 3DViewer importers can be included:
- .obj
- .dae
- .maya
- .max

**Comment by nlisker** [comment]
Didn't see this until now (you might want to notify on the openjfx issue). Sign me up!

.obj is by far the simplest format, supporting only mesh data and references to external materials. The other ones support animations, lighting etc. in addition.

What to import?
* Mesh data is of course a given.
* Animations will have to be imported since there's no way to contain them externally. In 3DViewer, only .ma files import animations, and only using quads (instead of the built in trigs of JavaFX). Tests Iv'e done show very poor performance of these animations.
* Materials can be imported directly, but that would require converting everything to Phong, which might cause some issues. Materials can be stored externally (via image files) and added in the javaFX side..
* Lighting will have to be converted to `PointLight`, or not imported at all. Lighting can be added in the JavaFX side.

As mentioned earlier, 3DViewer contains groundwork for polygon meshes (quads). It would be very nice to have this option as another subclass of `Mesh`, but that seems like extensive work if done properly, and maybe out of scope.

**Comment by jperedadnr** [comment]
About quads, the plan is to add them to FXyz-Core, that contains primitives and other shapes based on TriangleMesh. After all, the `PolygonMesh`/`PolygonMeshView` [approach](https://github.com/javafxports/openjdk-jfx/blob/develop/apps/samples/3DViewer/src/main/java/com/javafx/experiments/shape3d/PolygonMeshView.java#L276) is just _another _TriangleMesh_.  While it is a smart implementation and good enough for now, having other `Mesh` implementations in JavaFX would be great, but as you said, out of scope probably.

I'll try to create a first PR with the obj importer soon, including changes in FXyz-Core, and a sample in FXyz-Samples. And I'll notify on the openjfx issue of course.

**Comment by jperedadnr** [comment]
@nlisker I've created a [WIP] PR with [FXyz-Importers](https://github.com/FXyz/FXyz/pull/42), including obj for now. There is also a sample that can be run from FXyz-Samples.
I've added you as collaborator of the project, so I can add you as reviewer.

**Comment by jperedadnr** [comment]
@nlisker The next two importers are DAE and MAX

I've tested DAE with a few files and it fails to import them. I believe most of the issues are related to the import of the texture coordinates, but it will require some debugging and fixing.

As for the 3DS MAX ASE (Ascii) importer, I don't have a file to test it.

Do you think we try to should try to get DAE working first? What other importers can be contributed? Should we do a release of what we have so far?

**Comment by nlisker** [comment]
This is indeed a good time to discuss the next steps.

I think that there are 3 things we can do:
1. Flesh out the current Maya (and maybe OBJ) importer. I can submit a couple of tests that show problems with garbage collection (causing performance issues) and the `Optimizer`.
2. Get the DAE and 3DS importers working. I've never used these, but it shouldn't be hard to find models online. I did that for Maya.
3. Work on an FBX importer. The reason being that it's the most popular format currently and there is already an [importer](https://github.com/tesis-dynaware/fbx-importer) we can start with. It doesn't support animations and probably not textures either.

In my opinion, doing 1 is the best place to start because it will give us solid grounds for getting other importers in (shared classes etc.) and a reference to work by. I don't know how familiar you are with the code, but I don't have complete understanding of all of it yet, so focusing on one importer is better for me personally.

If that's fine with you, I can submit an issue(s) for the Maya importer and once these are resolved we can make a release with it.

**Comment by jperedadnr** [comment]
Agree, we want to have a release as soon as possible, to encourage others to use it and contribute. I guess OBJ/MAYA will have to do for now.

We can wait to have those issues first of course. In the meantime I'll try to enhance the sampler with a few more features (file choosing, animation controls)

**Comment by nlisker** [comment]
That reminds me that in my 3DViewer app I added a material tab:

![image](https://user-images.githubusercontent.com/37422899/47971983-ffc01380-e09f-11e8-8645-322728af97e0.png)

If it helps I can share the code. In general, I found this viewer very useful with its hierarchy table and transforms.

**Comment by jperedadnr** [comment]
@nlisker That's a good feature, but actually the FXyz-Samples has something quite similar for `TexturedMesh`, where you can set the material properties including the different textures (color, image, density map, pattern, ...), the bump map or the specular properties.

These features can be improved of course. For instance the hierarchy or transforms tabs could be really useful, and the materials tab should be extended to all the different materials imported with a model, not just one.

**Comment by FalcoTheBold** [comment]
Some time ago i worked on a custom gltf2.0-importer, which will not be continued for the time being i am afraid. 
But i would gladly provide the importer-sources to the FXYZ-project, in hope that my importer can be fully realized.

The current state of the importer:
Currently the mesh can be loaded and the material (only single material per mesh + converted to PhongMaterial) is already applied.
The armature is technically loaded, but has yet to be applied to the mesh. Animations aren't processed yet.
Most of the sources build upon the 3D-Viewer (PolygonMesh/-View, Maya joints, etc.) and was "inspired" by @jperedadnr's RiggedHand-project.

**Comment by jperedadnr** [comment]
I didn't know about that format, but any contribution is really welcome. 
@FalcoTheBold feel free to submit a PR, or if you want us to help you process missing parts first, provide the repo URL.

**Comment by FalcoTheBold** [comment]
@jperedadnr Yes, the format seems to be picking up speed only recently, unlike its predecessor.
I was basically looking for a simple and preferably not proprietary format that supports 3d-animations as well. There gltf was a godsend :)
If you are interested then you can have read at their official repo: https://github.com/KhronosGroup/glTF/blob/master/README.md

I prepared a repo for the sources now and will upload the files over the time.
Here is the URL: https://github.com/FalcoTheBold/gltf4FX

**Comment by FalcoTheBold** [comment]
@jperedadnr Hello, i need a little regarding the licensing of your old RiggedHand-project.
For the armature of the imported gltf-file i used the "Bone" class, which seems to have no license header, and also in general i am a little unsure how to implement parts of that said project into the upcoming repository (licensed under 3-clause BSD).
I would like to sort these license matters out before commiting my files.

**Comment by jperedadnr** [comment]
@FalcoTheBold The RiggedHand project was licensed under Apache License 2.0, but this wasn't added to the headers. On the other hand, FXyz is under 3-clause BSD, including the importers module.

Would be ok for you to include the FXyz BSD license in the source code you use from RiggedHand?

**Comment by jperedadnr** [comment]
@FalcoTheBold See this PR: #85, I've added a `JointChain` class that will be the equivalent for the `Bone` class. Would that work for you?

**Comment by FalcoTheBold** [comment]
@jperedadnr Hello, i the class looks interesting, but i added the license header to the old Bone-class and use this one at the moment.
Right now i face problems at how to set up the project in order to be integrated and at the same time use FXYZ well.
The idea for this project was to stay relatively lightweight, to be able to pull this project in and out when needed.
The code is finally up now by the way, sadly my past self made some mistakes and at the moment the mesh cant be loaded because of an error regarding the smoothing groups.
Here the repo again: https://github.com/FalcoTheBold/gltf4FX
It also requires these repos in order to fully work too: 
- https://github.com/FalcoTheBold/VDFX-base
- https://github.com/FalcoTheBold/VDFX-asset3d

**Comment by FalcoTheBold** [comment]
To at least sweeten the current dilemma a little, here a picture of the result of an imported gltf-asset before the mistakes were implemented:

![20180919_121700](https://user-images.githubusercontent.com/44414891/53081760-c2bb4800-34fb-11e9-9580-3bfce8e2ba16.png)

As one can see the position of the skeleton/armature seems mostly correct, but the bones take wrong rotation values, albeit almost close to the source pose in shape.
I assumed it might be related to how the axes in JavaFX are set up in relations to the previous modelling software (Blender) and thus i tried many combinations of inversing the rotation values (multiplying by negative values, minor adjustment, etc), but to no avail for the moment.
It is still just a matter of testing until the right approach comes up though.

If one wonders, the long stick-bone coming out from the ground is from the "Root Bone", it is supposed to be like that, just the bone-class is not able to differentiate between connected and unconnected modes yet.

**Comment by jperedadnr** [comment]
@FalcoTheBold Looks good. 
I've spent quite a lot of time too on finding out the right maths for the `JointChain`, so this is why I'd suggest you give it a try instead of the `Bone` class. 
If you test the PR #85 you can play around with the Maya sample, and see for yourself how I used it based on the forest of joints.

Regarding adding your project to FXyz, for starters we'll need a gradle project. You could reuse all the existing classes (like `SkinningMesh`), and it would be good to have one single project without dependencies other than the third party libraries it needs.

**Comment by jperedadnr** [comment]
Done as FXyz-Importers is there since FXyz 0.5.0. While it is not complete (it has only a few importers), the issue can be closed, and new issues should be created.
