### ISSUE TITLE
How to update Polyline3D once created?

### ISSUE THREAD

**Issue by phamvanthanh** [FXyz/FXyz#90]
Hi,
Is that possible?

**Comment by Birdasaur** [comment]
hi phamvanthanh.  What exactly would you like to update in the Polyline3D object?  The color?  The points themselves?

**Comment by phamvanthanh** [comment]
Yes. I would like to update points, change their coordinates.

**Comment by Birdasaur** [comment]
There are two ways you can do it. One way would be to simply remove the old PolyLine3D from the Scene and replace it with a new PolyLine3D with the updated coordinates.  This is the simplest way and should be fine if you are not performing the change very often.

However that might be painful to remove and then add PolyLine3D objects to the scene if you must do it very frequently or for many different instances.  A slightly better way would be to alter the MeshView for each PolyLine3D that is already in the scene.  The easiest way to do that would be to create the new PolyLine3D (letting the mesh layout algorithm map the points to triangles) and then just set the MeshView of the existing PolyLine3D.  You do have to instantiate a new PolyLine3D object but you never have to remove and then add the object to the scene.  Here is something I did to make an animated trajectory... basically a PolyLine3D that travels around the screen like a comet:

`                        //Update the mesh
                        PolyLine3D nextPoly = new PolyLine3D(points.subList(startTail, headTail), width, color, LineType.TRIANGLE);
                        meshView.setMesh(nextPoly.meshView.getMesh());`

where meshView is the MeshView object of the current PolyLine3D already on screen.

This seems to be more efficient than the previous approach and animates very well, yet is still fairly simple.  You may still have memory issues if you are doing a huge number of polylines. If that is the case, there are more complicated ways to update the mesh itself.... but it requires setting the low level "faces" and "points" array. This is a pain in the butt which is handled by the PolyLine3D::buildTriangleTube() method, but unfortunately it is currently private.  You could copy that code into your own utility method and then overwrite the arrays of the the MeshView.TriangleMesh object.

**Comment by phamvanthanh** [comment]
Thanks for your thorough explaination.

Since it has List<Point3D> as constructor argument. I think it should have setPoints and addPoint to easily update.

The Ribbon is currently drawing its with on Z so so we cannot see PolyLine3D in XY plane.

Both TriangleTube and Ribbon are not showing square ends.

Below is one of my testing implementation of 3D Polyline.

![image](https://user-images.githubusercontent.com/24784468/57060428-941fd180-6ce3-11e9-9e9b-2b4a7fde26bd.png)

I do not know if this idea should be applied to PolyLine3D

**Comment by Birdasaur** [comment]
I'm not sure what I'm looking at exactly with the picture but we already have test examples for the PolyLine3D that you can play with. Here are some answers to your questions:

> The Ribbon is currently drawing its width on Z so we cannot see PolyLine3D in XY plane.
Correct. That is by design. 
The ribbon winding algorithm is the absolute minimum amount of triangles necessary to create the line mesh. The sacrifice is that if your camera is _perfectly_ aligned with the Z plane the mesh becomes vanishingly small.  That's why we made the TriangleTube.

> Both TriangleTube and Ribbon are not showing square ends.
Correct. That is by design.
Neither are square type mesh winding patterns. The Ribbon winding algorithm is flat for the reasons described above and the TriangleTube will feature some form of a .... Triangle.... because it is essentially creating a Z dimension depth at a set width from the current point in the list. This is done at the sacrifice of performance, ie... 33% more triangles and vertices are created over the Ribbon algorithm.

> it should have setPoints 
Having a setPoint() method might be useful in that it would spare the user the pain of temporarily creating a new PolyLine3D object. However there would not be any performance gain as it would simply be calling the ::buildTriangleTube() method anyways.  I will look into it.

> and addPoint to easily update.
Making an addPoint() method would be difficult both from an implementation and a performance standpoint. It is technically possible to dig down into the low level points, faces and texture coordinates arrays and reorder the indices so that the triangle winding patterns are updated, thus updating the TriangleMesh.  Then you would have to update the MeshView of  the PolyLine3D to reload the Mesh, thus updating the Scene. 
After all that work... you might as well create a new PolyLine3D object.  However you're welcome to look at the ::buildTriangleTube() method and see if you can find an easy way to do it. 


If you are looking for a more "Round Tube" type implementation then we have other examples which demonstrate that. The sacrifice you will make is complexity and again performance as these implementations have many more vertices and faces. They are overkill for most applications that just want to draw a line between a few points in the scene but they do look very nice.
